In [2]:
import numpy as np
import scipy

In [3]:
print("np.version", np.__version__)
print("scipy.version", scipy.__version__)

np.version 1.23.5
scipy.version 1.10.1


In [ ]:
a = np.arange(24).reshape((4, 3, 2))
print(a)
a = a.transpose()
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]


In [6]:
a[1, :, :]= [[0 , 1], [2, 3], [4, 5]]
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [ ]:
from scipy.s    

In [ ]:
a[1, :, :]= [[0 , 1], [2, 3], [4, 5]]


[[[ 0  0 12 18]
  [ 2  2 14 20]
  [ 4  4 16 22]]

 [[ 1  1 13 19]
  [ 3  3 15 21]
  [ 5  5 17 23]]]
